### PR TITLE
Deliverized version of PR #1

### PR DESCRIPTION
**Pull request by schisamo**
This PR replaces https://github.com/chef-cookbooks/remote_install/pull/1. 

/cc @chef-cookbooks/engineering-services

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by schisamo** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: dc114dcf-99f3-434e-901f-c581a67d2aed approved by: @schisamo

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by schisamo** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: dc114dcf-99f3-434e-901f-c581a67d2aed delivered by: @schisamo

**Pull request merged**
