### PR TITLE
the -v flag for tar is unsupported on older and bsd versions of tar, …

### PR DESCRIPTION
**Pull request by scotthain**
…which is an issue on older platforms

### CODE REVIEW

**Comment by yzl** [comment]
:+1:

**Comment by schisamo** [comment]
Have we run the integration tests against Ubuntu and CentOS?

**Comment by scotthain** [comment]
@schisamo - I didn't think it was necessary since it's a minor non-additive change. I'll run them now.

**Comment by scotthain** [comment]
@schisamo ran all the tests locally - turns out there's no way they could have worked in the past, not sure what the deal was there. I've updated them and they all work now.

**Comment by schisamo** [comment]
@scotthain Awesome! :+1: 

I'll work on wiring all integration tests to run in Travis (like we do for the `omnibus` and `languages` cookbooks).

**Pull request merged**
