### PR TITLE
Add Delivery config

### PR DESCRIPTION
**Pull request by schisamo**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jtimberman** [comment]
@delivery approve

**Comment by jtimberman** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 7a1d5405-0a81-4016-bcf3-42d085290351 approved by: @jtimberman

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by schisamo** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: 7a1d5405-0a81-4016-bcf3-42d085290351 delivered by: @schisamo

**Pull request merged**
